
project_id = "pakrraqbjbkkbdnwkkbt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
additional_redirect_urls = ["https://pakrraqbjbkkbdnwkkbt.supabase.co"]
jwt_expiry = 3600
enable_anonymous_sign_ins = false
enable_signup = true
enable_confirmations = false

[functions.send-proposal-email]
verify_jwt = false

[functions.generate-proposal-template]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.get-product-prices]
verify_jwt = false

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.setup-telegram-webhook]
verify_jwt = false

[functions.telegram-notifications]
verify_jwt = false
