// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pakrraqbjbkkbdnwkkbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBha3JyYXFiamJra2Jkbndra2J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTUwODIsImV4cCI6MjA2Nzk5MTA4Mn0.xo-EnoRKGlozIE5MirUu_WRR4ljgX9HFQMKxvNaKl8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});